-- CREATE TABLE nvp_user (
--   user_id SERIAL PRIMARY KEY,
--   first_name VARCHAR(250),
--   last_name VARCHAR(250),
--   email VARCHAR(250) NOT NULL,
--   hash VARCHAR(30) NOT NULL
-- )

-- INSERT INTO nvp_user (first_name,last_name,email,hash)
-- VALUES(
--   'chris',
--   'deMontigny',
--   'my email',
--   'pass'
-- )